=== avilxrd/si_codes/xml/curriculo_dtd/shortCV.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT cv (nome, sexo, dataNascimento, end, instituicao, fone, email, url, titulacao+, pubs) >
<!ELEMENT nome (#PCDATA) >
<!ELEMENT sexo (#PCDATA) >
<!ELEMENT dataNascimento (#PCDATA) >
  
<!ELEMENT end (rua?, nro?, bairro?, cep?, cidade, estado?, pais?) >
<!ELEMENT rua (#PCDATA) >
<!ELEMENT nro (#PCDATA) >
<!ELEMENT bairro (#PCDATA) >
<!ELEMENT cep (#PCDATA) >
<!ELEMENT cidade (#PCDATA) >
<!ELEMENT estado (#PCDATA) >
<!ELEMENT pais (#PCDATA) >

<!ELEMENT instituicao (nome, end?) >
<!ELEMENT fone (telefone, ramal?, fax?) >
<!ELEMENT telefone (#PCDATA) >
<!ELEMENT ramal (#PCDATA) >
<!ELEMENT fax (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT url (#PCDATA) >

<!ELEMENT titulacao (nome, instituicao, tese, orientador) >
<!ELEMENT tese (#PCDATA) >
<!ELEMENT orientador (nome, sobrenome) >

<!ELEMENT pubs (pub+) >
<!ELEMENT pub (autores, titulo, evento, end, ano) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT autores (autor+) >
<!ELEMENT autor (sobrenome, nome) >
<!ELEMENT sobrenome (#PCDATA) >
<!ELEMENT evento (#PCDATA) >
<!ELEMENT ano (#PCDATA) >

=== avilxrd/si_codes/xml/curriculo_dtd/shortCV.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cv SYSTEM "shortCV.dtd">

<cv> 
    <nome>Miguel Avila de Oliveira</nome>
    <sexo>Masculino</sexo>
    <dataNascimento>16/08/2004</dataNascimento>
    
    <end>
        <rua>Rua dos Andradas</rua>
        <nro>277</nro>
        <bairro>Passo d'Areia</bairro>
        <cep>97020-040</cep>
        <cidade>Santa Maria</cidade>
        <estado>Rio Grande do Sul</estado>
        <pais>Brasil</pais>
    </end>
    
    <instituicao>
        <nome>Universidade Federal de Santa Maria</nome>
        <!-- <end></end> -->
    </instituicao>
    
    <fone>
        <telefone>(55) 99123-4313</telefone>
        <!-- <ramal></ramal> -->
        <!-- <fax></fax> -->
    </fone>
    <email>miguelaviladeoliveira@gmail.com</email>
    <url>miguel.com.br</url>
    
    <titulacao>
        <nome>Tec. em Informática para Internet</nome>
        <instituicao>
            <nome>CTISM</nome>
            <end>
                <rua>Av. Roraima</rua>
                <cidade>Santa Maria</cidade>
            </end>
        </instituicao>
        <tese>Relatório de Estágio</tese>
        <orientador>
            <nome>Fabio</nome>
            <sobrenome>Franciscato</sobrenome>
        </orientador>
    </titulacao>

    <pubs>
        <pub>
            <autores>
                <autor>
                    <sobrenome>Avila de Oliveira</sobrenome>
                    <nome>Miguel</nome>
                </autor>
            </autores>
            <titulo>Relatorio de Estagio</titulo>
            <evento>CTISM</evento>
            <end>
                <cidade>Santa Maria</cidade>
            </end>
            <ano>2025</ano>
        </pub>
    </pubs>

</cv>
